version: 2.1

jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: Install Python
          command: |
            sudo apt update
            sudo apt install -y python3-pip

      - run:
          name: Install Dependencies
          command: |
            pip3 install -r requirements.txt

      - run:
          name: Run Training Pipeline
          command: |
            python3 -m pipeline.training_pipeline

      - run:
          name: Build Docker Image
          command: |
            docker build -t iris-app .
      
      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login \
            -u "$DOCKER_USERNAME" \
            --password-stdin

      - run:
          name: Build Image
          command: |
            docker build -t $DOCKER_USERNAME/iris-app:latest .

      - run:
          name: Push Image
          command: |
            docker push $DOCKER_USERNAME/iris-app:latest

workflows:
  version: 2

  build_workflow:
    jobs:
      - build